version: '3.8'
services:
  demodocker-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: demodocker/api
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx300m -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
